version: '3.8'

services:
  web:
    image: programminghero/saleor:3.7.27
    build:
      context: ../
    depends_on:
      - db
      - cache
    ports:
      - "8008:8000"
    environment:
      - DEBUG=True
      - ALLOWED_HOSTS=*
      - ALLOWED_CLIENT_HOSTS=*
      - RSA_PRIVATE_KEY
      - EMAIL_HOST=smtp-relay.sendinblue.com
      - EMAIL_PORT=587
      - EMAIL_HOST_USER=anwar.hussen.pro@gmail.com
      - DATABASE_URL=postgresql://django_traefik:django_traefik@db:5432/django_traefik
      - REDIS_URL=redis://cache:6379/0
      - CELERY_BROKER_URL=redis://cache:6379/0
      - CELERY_RESULT_BACKEND=redis://cache:6379/0
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`saleor.helloanwar.com`)"
      - "traefik.http.routers.django.tls=true"
      - "traefik.http.routers.django.tls.certresolver=letsencrypt"

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data_new2:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=django_traefik
      - POSTGRES_PASSWORD=django_traefik
      - POSTGRES_DB=django_traefik
  cache:
    image: redis:latest
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
#  traefik:
#    image: traefik:latest
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - "/var/run/docker.sock:/var/run/docker.sock:ro"
#      - "./traefik-public-certificates:/certificates"
#      - "./traefik.prod.toml:/etc/traefik/traefik.toml"
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.dashboard.rule=Host(`traefik.helloanwar.com`)"
#      - "traefik.http.routers.dashboard.tls=true"
#      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
#      - "traefik.http.routers.dashboard.service=api@internal"
#      - "traefik.http.routers.dashboard.middlewares=auth"
#      - "traefik.http.middlewares.auth.basicauth.users=testuser:$$apr1$$jIKW.bdS$$eKXe4Lxjgy/rH65wP1iQe1"

volumes:
  #  traefik-public-certificates:
  postgres_data_new2:
  cache:
    driver: local
