name: Docker Build and Push

on:
  release:
    types:
      - created

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get version from tag
        id: get-version
        run: echo "::set-output name=version::$(echo ${{ github.ref }} | sed -n 's|^refs/tags/v\([0-9.]*\)$|\1|p')"

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            latest
            ${{ secrets.DOCKERHUB_USERNAME }}/saleor:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/saleor:${{ steps.get-version.outputs.version }}
