name: Docker Build and Push

on:
  release:
    types:
      - created

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get version from tag
        id: get-version
        run: echo "::set-output name=version::$(echo ${{ github.ref }} | sed -n 's|^refs/tags/v\([0-9.]*\)$|\1|p')"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            programminghero/saleor:latest
            programminghero/saleor:${{ steps.get-version.outputs.version }}
          cache-from: type=registry,ref=programminghero/saleor:buildcache
          cache-to: type=registry,ref=programminghero/saleor:buildcache,mode=max
